//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXTEST_WXMAILPATALETA_WXCRAFTER_BASE_CLASSES_H
#define WXTEST_WXMAILPATALETA_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/datectrl.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/statline.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class MainDialogBaseClass : public wxDialog
{
protected:
    wxPanel* m_panel17;
    wxDatePickerCtrl* m_datePicker23;
    wxStaticText* m_staticText27;
    wxTextCtrl* m_saldoAnteriorTextCtrl29;
    wxStaticText* m_staticText31;
    wxTextCtrl* m_creditoConcedidoTextCtrl33;
    wxStaticText* m_staticText35;
    wxTextCtrl* m_creditoCobradoTextCtrl37;
    wxStaticText* m_staticText39;
    wxTextCtrl* m_saldoFinalTextCtrl41;
    wxStaticLine* m_staticLine51;
    wxStaticLine* m_staticLine53;
    wxStaticText* m_staticText55;
    wxTextCtrl* m_banco1textCtrl57;
    wxDatePickerCtrl* m_vencimiento1banco1datePicker59;
    wxTextCtrl* m_importe1banco1textCtrl61;
    wxStaticText* m_staticText63;
    wxDatePickerCtrl* m_vencimiento2banco1datePicker69;
    wxTextCtrl* m_importe2banco1textCtrl71;
    wxStaticText* m_staticText73;
    wxTextCtrl* m_banco2textCtrl75;
    wxDatePickerCtrl* m_vencimiento1banco2datePicker77;
    wxTextCtrl* m_importe1banco2textCtrl79;
    wxStaticText* m_staticText81;
    wxDatePickerCtrl* m_vencimiento2banco2datePicker85;
    wxTextCtrl* m_importe2banco2textCtrl87;
    wxStaticText* m_staticText89;
    wxTextCtrl* m_banco3textCtrl91;
    wxDatePickerCtrl* m_vencimiento1banco3datePicker93;
    wxTextCtrl* m_importe1banco3textCtrl95;
    wxStaticText* m_staticText97;
    wxDatePickerCtrl* m_vencimiento2banco3datePicker101;
    wxTextCtrl* m_importe2banco3textCtrl103;
    wxStaticText* m_staticText127;
    wxTextCtrl* m_importeTotalVencimientosTextCtrl133;
    wxStaticLine* m_staticLine135;
    wxStaticLine* m_staticLine137;
    wxStaticLine* m_staticLine139;
    wxStaticLine* m_staticLine141;
    wxStaticText* m_staticText109;
    wxTextCtrl* m_totalPagaresEnCarteraTextCtrl113;
    wxStaticText* m_staticText115;
    wxDatePickerCtrl* m_prevision1datePicker117;
    wxTextCtrl* m_importePrevision1textCtrl119;
    wxStaticText* m_staticText121;
    wxDatePickerCtrl* m_prevision2datePicker123;
    wxTextCtrl* m_importePrevision2textCtrl125;
    wxStaticLine* m_staticLine15;
    wxButton* m_buttonOK;
    wxButton* m_buttonCancel;

protected:

public:
    wxDatePickerCtrl* GetDatePicker23() { return m_datePicker23; }
    wxStaticText* GetStaticText27() { return m_staticText27; }
    wxTextCtrl* GetSaldoAnteriorTextCtrl29() { return m_saldoAnteriorTextCtrl29; }
    wxStaticText* GetStaticText31() { return m_staticText31; }
    wxTextCtrl* GetCreditoConcedidoTextCtrl33() { return m_creditoConcedidoTextCtrl33; }
    wxStaticText* GetStaticText35() { return m_staticText35; }
    wxTextCtrl* GetCreditoCobradoTextCtrl37() { return m_creditoCobradoTextCtrl37; }
    wxStaticText* GetStaticText39() { return m_staticText39; }
    wxTextCtrl* GetSaldoFinalTextCtrl41() { return m_saldoFinalTextCtrl41; }
    wxStaticLine* GetStaticLine51() { return m_staticLine51; }
    wxStaticLine* GetStaticLine53() { return m_staticLine53; }
    wxStaticText* GetStaticText55() { return m_staticText55; }
    wxTextCtrl* GetBanco1textCtrl57() { return m_banco1textCtrl57; }
    wxDatePickerCtrl* GetVencimiento1banco1datePicker59() { return m_vencimiento1banco1datePicker59; }
    wxTextCtrl* GetImporte1banco1textCtrl61() { return m_importe1banco1textCtrl61; }
    wxStaticText* GetStaticText63() { return m_staticText63; }
    wxDatePickerCtrl* GetVencimiento2banco1datePicker69() { return m_vencimiento2banco1datePicker69; }
    wxTextCtrl* GetImporte2banco1textCtrl71() { return m_importe2banco1textCtrl71; }
    wxStaticText* GetStaticText73() { return m_staticText73; }
    wxTextCtrl* GetBanco2textCtrl75() { return m_banco2textCtrl75; }
    wxDatePickerCtrl* GetVencimiento1banco2datePicker77() { return m_vencimiento1banco2datePicker77; }
    wxTextCtrl* GetImporte1banco2textCtrl79() { return m_importe1banco2textCtrl79; }
    wxStaticText* GetStaticText81() { return m_staticText81; }
    wxDatePickerCtrl* GetVencimiento2banco2datePicker85() { return m_vencimiento2banco2datePicker85; }
    wxTextCtrl* GetImporte2banco2textCtrl87() { return m_importe2banco2textCtrl87; }
    wxStaticText* GetStaticText89() { return m_staticText89; }
    wxTextCtrl* GetBanco3textCtrl91() { return m_banco3textCtrl91; }
    wxDatePickerCtrl* GetVencimiento1banco3datePicker93() { return m_vencimiento1banco3datePicker93; }
    wxTextCtrl* GetImporte1banco3textCtrl95() { return m_importe1banco3textCtrl95; }
    wxStaticText* GetStaticText97() { return m_staticText97; }
    wxDatePickerCtrl* GetVencimiento2banco3datePicker101() { return m_vencimiento2banco3datePicker101; }
    wxTextCtrl* GetImporte2banco3textCtrl103() { return m_importe2banco3textCtrl103; }
    wxStaticText* GetStaticText127() { return m_staticText127; }
    wxTextCtrl* GetImporteTotalVencimientosTextCtrl133() { return m_importeTotalVencimientosTextCtrl133; }
    wxStaticLine* GetStaticLine135() { return m_staticLine135; }
    wxStaticLine* GetStaticLine137() { return m_staticLine137; }
    wxStaticLine* GetStaticLine139() { return m_staticLine139; }
    wxStaticLine* GetStaticLine141() { return m_staticLine141; }
    wxStaticText* GetStaticText109() { return m_staticText109; }
    wxTextCtrl* GetTotalPagaresEnCarteraTextCtrl113() { return m_totalPagaresEnCarteraTextCtrl113; }
    wxStaticText* GetStaticText115() { return m_staticText115; }
    wxDatePickerCtrl* GetPrevision1datePicker117() { return m_prevision1datePicker117; }
    wxTextCtrl* GetImportePrevision1textCtrl119() { return m_importePrevision1textCtrl119; }
    wxStaticText* GetStaticText121() { return m_staticText121; }
    wxDatePickerCtrl* GetPrevision2datePicker123() { return m_prevision2datePicker123; }
    wxTextCtrl* GetImportePrevision2textCtrl125() { return m_importePrevision2textCtrl125; }
    wxPanel* GetPanel17() { return m_panel17; }
    wxStaticLine* GetStaticLine15() { return m_staticLine15; }
    wxButton* GetButtonOK() { return m_buttonOK; }
    wxButton* GetButtonCancel() { return m_buttonCancel; }
    MainDialogBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxT("Previsión de tesorería"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~MainDialogBaseClass();
};

#endif
